export const ActionTypes = {
  MOVIES_LOADING: "LOADING",
  MOVIES_SUCCESS: "SUCCESS",
  MOVIES_ERROR: "ERROR",
  GENRES_LOADING: "GENRES_LOADING",
  GENRES_SUCCESS: "GENRES_SUCCESS",
  GENRES_ERROR: "GENRES_ERROR",
};
